#!/usr/bin/env ruby

require 'rubygems'
require 'celluloid'

class Thingy
  include Celluloid

  def initialize(name)
    @name = name
  end

  def start
    puts "begin #{@name}"
    sleep 3
    puts "done #{@name}"
    terminate
  end
end

actors = []
3.times do
  actors << runner = Thingy.new("keith")
  runner.async.start
end

until actors.select(&:alive?).empty?
  sleep 0.5
end
